baseURL = 'https://polite-stone-0de443110.2.azurestaticapps.net/'
languageCode = 'en-us'
title = 'PDF Demo'
theme = 'ananke'


[[module.imports]]
    path = "github.com/AlanTanner/pdfjs-hugo-module"
    disabled = false